version: '3.8'



services: 
  db: 
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_password}
      POSTGRES_DB: ${DB_name}
    container_name: tienda01DB  
    volumes:
      - ./data:/var/lib/postgresql/data